name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run lint || echo "No lint script"
      - run: npm run typecheck || echo "No typecheck script"
      - run: npm run test -- --coverage || echo "No test script"
